spring:
#  datasource:
#    url: jdbc:postgresql://ec2-54-221-221-153.compute-1.amazonaws.com:5432/d4tuufs2vrjb62?sslmode=require
#    username: ugwiaadjxxnpce
#    password: 39bb54a78b0e50538985acf2c2a2f39c03a98973d57cfb98b0ffab5909d510ac
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_meta data_defaults: false
        show_sql: true