spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/venite
#    username: zaki
#    password: 1234
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_meta data_defaults: false
        show_sql: true
        hbm2ddl:
          auto: create-drop